# name: Docs

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: true

# permissions:
#   pull-requests: write
#   contents: write

# on:
#   push:
#     branches:
#       - main
#     paths: 
#       - '.docs/**'

# defaults:
#   run:
#     working-directory: ./.docs

# jobs:
#   build-test:
#     name: 📚 Main
#     runs-on: ${{ matrix.os }}
#     timeout-minutes: 5
#     defaults:
#       run:
#         working-directory: ./.docs


#     strategy:
#       matrix:
#         os: [macos-14]
        
#     steps:
#       - uses: actions/checkout@v4
#       - uses: pnpm/action-setup@v2

      # hooks send 


      # - run: corepack enable
      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: '20'
      #     cache: pnpm

      # - name: Cache
      #   uses: actions/cache@v4
      #   with:
      #     path: |
      #       ./.eslintcache
      #     key: ${{ runner.os }}-cache-${{ hashFiles('**/pnpm-lock.yaml') }}
      #     restore-keys: |
      #       ${{ runner.os }}-cache-${{ hashFiles('**/pnpm-lock.yaml') }}


      # - name: 📦 Install dependencies
      #   run: pnpm install

      # - name: 🚀 Build
      #   run: pnpm build

      # - name: Nitro Deploy
      #   uses: nitrodeploy/nitrodeploy-github-action@v0.4.2
      #   with:
      #     TYPE: 'vitepress'
      #     AUTO_BUILD: false
      #     EXPORT_FOLDER: '.docs/.vitepress/dist'
      #   env:
      #     # The Nitro Deploy token to use to authenticate with the Nitro Deploy API.
      #     NITRO_DEPLOY_TOKEN: ${{ secrets.NITRO_DEPLOY_TOKEN }}