require_relative '../../../../node_modules/.pnpm/@capacitor+ios@6.0.0-rc.0_@capacitor+core@6.0.0-rc.0/node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '13.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../../../node_modules/.pnpm/@capacitor+ios@6.0.0-rc.0_@capacitor+core@6.0.0-rc.0/node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../../../node_modules/.pnpm/@capacitor+ios@6.0.0-rc.0_@capacitor+core@6.0.0-rc.0/node_modules/@capacitor/ios'
  pod 'CapacitorActionSheet', :path => '../../../../node_modules/.pnpm/@capacitor+action-sheet@6.0.0-rc.0_@capacitor+core@6.0.0-rc.0/node_modules/@capacitor/action-sheet'
  pod 'CapacitorApp', :path => '../../../../node_modules/.pnpm/@capacitor+app@6.0.0-rc.0_@capacitor+core@6.0.0-rc.0/node_modules/@capacitor/app'
  pod 'CapacitorAppLauncher', :path => '../../../../node_modules/.pnpm/@capacitor+app-launcher@6.0.0-rc.0_@capacitor+core@6.0.0-rc.0/node_modules/@capacitor/app-launcher'
  pod 'CapacitorBackgroundRunner', :path => '../../../../node_modules/.pnpm/@capacitor+background-runner@1.0.5_@capacitor+core@6.0.0-rc.0/node_modules/@capacitor/background-runner'
  pod 'CapacitorBrowser', :path => '../../../../node_modules/.pnpm/@capacitor+browser@6.0.0-rc.0_@capacitor+core@6.0.0-rc.0/node_modules/@capacitor/browser'
  pod 'CapacitorDevice', :path => '../../../../node_modules/.pnpm/@capacitor+device@6.0.0-rc.0_@capacitor+core@6.0.0-rc.0/node_modules/@capacitor/device'
  pod 'CapacitorDialog', :path => '../../../../node_modules/.pnpm/@capacitor+dialog@6.0.0-rc.0_@capacitor+core@6.0.0-rc.0/node_modules/@capacitor/dialog'
  pod 'CapacitorFilesystem', :path => '../../../../node_modules/.pnpm/@capacitor+filesystem@6.0.0-rc.0_@capacitor+core@6.0.0-rc.0/node_modules/@capacitor/filesystem'
  pod 'CapacitorGeolocation', :path => '../../../../node_modules/.pnpm/@capacitor+geolocation@6.0.0-rc.0_@capacitor+core@6.0.0-rc.0/node_modules/@capacitor/geolocation'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
