name: autofix.ci
on:
  pull_request:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  autofix:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ./.eslintcache
            ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-cache
          restore-keys: |
            ${{ runner.os }}-cache

      - name: 📦 Install dependencies
        run: pnpm install
        

      - name: Fix lint issues
        run: npm run lint:fix
      - uses: autofix-ci/action@2891949f3779a1cafafae1523058501de3d4e944
        with:
          commit-message: "fix: lint issues"